### ISSUE TITLE
Fix _service { sdl } render to hide federated fields

### ISSUE THREAD

**Issue by kdawgwilk** [DivvyPayHQ/absinthe_federation#21] opened 2021-09-23 06:33 UTC
While implementing this PR https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/35 I found we are not filtering federated schema fields from the SDL render like we should

**Comment by kdawgwilk** [comment] 2021-11-02 18:35
This was reverted in #29 and we need to look at taking a different approach

**Comment by kzlsakal** [comment] 2022-04-14 17:12
Reopening this since #42 was reverted by #48

**Comment by lorgio-jimenez** [comment] 2022-05-13 00:00
Is there a version of the gem that does render this properly? We're switching over from using a mesh server to using this library, and this is a serious blocker for us to deploy with.

**Comment by kzlsakal** [comment] 2022-05-13 03:40
> Is there a version of the library that does render this properly?

The SDL rendered with v0.2.4 is compliant with [Gateway](https://github.com/apollographql/federation/tree/main/gateway-js) 2 and it works without any problems. We currently use it in production.

The issue is about full compliance with Apollo Federation specs. Rendering these extra fields in the SDL doesn't affect the functionality as far as I can tell. 

To answer your question though, unfortunately, we do not have a version where this issue is fixed without introducing bugs like https://github.com/DivvyPayHQ/absinthe_federation/issues/47 or https://github.com/DivvyPayHQ/absinthe_federation/issues/28.

**Comment by kzlsakal** [comment] 2022-05-13 03:47
While looking at this, I noticed that there might have been an update on Apollo Federation docs. It mentions:

> Unlike introspection, the sdl field's returned string includes federation-specific directives like `@key`.


https://www.apollographql.com/docs/federation/subgraphs/#query_service

This may be implying that we don't need to omit federation-specific fields from the SDL render after all. Any thoughts @kdawgwilk?

**Comment by kdawgwilk** [comment] 2022-05-13 04:27
You are supposed to include the directives themselves on each field but it's the federated type definitions that are not recommended to be present eg `union _Entity` or directive definitions.  Absinthe does a few optimizations like eagerly stripping out types that are not referenced in any accessible way in the schema which has been causing us problems.  We have a pretty good trade off in place right now that should work great.  What issues are you running into?

**Comment by kroehre** [comment] 2022-05-27 16:44
`_resolveReference` fields are appearing in the schema also

**Comment by kdawgwilk** [comment] 2022-05-27 17:17
@kzlsakal we could prob strip out those `_resolveReference` fields no matter what even if there is no `_Entity` type

**Comment by kdawgwilk** [comment] 2022-06-27 21:19
This PR will strip out the `_resolveReference` fields from the SDL render https://github.com/DivvyPayHQ/absinthe_federation/pull/55 which helps to partially resolve this issue

**Comment by dariuszkuc** [comment] 2024-02-06 17:13
FYI federation v1 required SDL modifications to strip out the fed definitions but fed v2 accepts full schemas -> there is no need to filter anything so you could just print out whole schema.

**Comment by kzlsakal** [comment] 2024-12-22 05:08
Closing this due to inactivity. Also potential duplicate of https://github.com/DivvyPayHQ/absinthe_federation/issues/77, we can continue there if there is an interest in stripping these fields.

**Closed by kzlsakal** 2024-12-22 05:08 UTC
Labels: bug
